### ISSUE TITLE
ninja: error: pkg/mc/myr.ninja

### ISSUE THREAD

**Issue by hovind** [michaelforney/oasis#4]
I am following the installation guide, and run into the following issue when issuing

`ninja commit`
> ninja: error: pkg/mc/myr.ninja:1: expected ':', got '|' ($ also escapes ':')
> build $outdir/lib/sys/sys.o | $outdir/lib/sys/sys.use: mc $srcdir/lib/sy...
>                             ^ near here

Not at all a pressing issue, as I don't need Myrddin, and it might be that I am doing something wrong. Thanks a lot for all of the effort you put into this system, it is greatly appreciated!

**Comment by michaelforney** [comment]
The syntax failing here is implicit outputs, which looks like it was added in version 1.7. I'll update it to set `ninja_required_version = 1.7` so that the version requirement is clear.

Here are some possible workarounds:
- Update to ninja 1.7 or newer.
- Build samurai: `git submodule update --init pkg/samurai/src && make -C pkg/samurai/src`.
- Disable mc by commenting out `subgen 'mc'` in `pkg/gen.lua` (since I think that is the only place I'm using implicit outputs).
